In [15]:
!pip install pandas mysql-connector-python sqlalchemy

Requirement already satisfied: pandas in C:\Users\sreeja pallerla\AppData\Local\Programs\Python\Python314\Lib\site-packages (3.0.3)
Requirement already satisfied: mysql-connector-python in C:\Users\sreeja pallerla\AppData\Local\Programs\Python\Python314\Lib\site-packages (9.7.0)
Requirement already satisfied: sqlalchemy in C:\Users\sreeja pallerla\AppData\Local\Programs\Python\Python314\Lib\site-packages (2.0.50)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\sreeja pallerla\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\sreeja pallerla\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\sreeja pallerla\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: greenlet>=1 in C:\Users\sreeja pallerla\AppData\Local\Programs\Python\Python314\Lib\site-packages (from sqlalchemy) (3.5.1)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\sreeja pallerla\AppData\Local\Programs\Python\Python314\Lib\site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: six>=1.5 in C:\Users\sreeja pallerla\AppData\Local\Programs\Python\Python314\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: C:\Users\sreeja pallerla\AppData\Local\Programs\Python\Python314\python.exe -m pip install --upgrade pip

In [5]:
import pandas as pd

print("Pandas Installed Successfully")

Pandas Installed Successfully

In [6]:
import mysql.connector

print("MySQL Connector Installed Successfully")

MySQL Connector Installed Successfully

In [7]:
from sqlalchemy import create_engine

print("SQLAlchemy Installed Successfully")

SQLAlchemy Installed Successfully

In [1]:
import pandas as pd

df = pd.read_csv("customers.csv")

df.head()

,CustomerID,CustomerName,City,Email,Age,JoinDate,TotalPurchase
0,1,Amit Sharma,Delhi,amit@gmail.com,28.0,1/10/2025,12500.0
1,2,Priya Rao,Chennai,priya@gmail.com,34.0,1/15/2025,22000.0
2,3,Rahul Verma,Mumbai,rahul@gmail.com,41.0,2/2/2025,18500.0
3,4,Sneha Iyer,Bengaluru,sneha@gmail.com,29.0,2/12/2025,9800.0
4,5,Kiran Kumar,Hyderabad,kiran@gmail.com,37.0,3/5/2025,31000.0

In [2]:
import pandas as pd
from sqlalchemy import create_engine

In [3]:
df = pd.read_csv("customers.csv")
df.head()

,CustomerID,CustomerName,City,Email,Age,JoinDate,TotalPurchase
0,1,Amit Sharma,Delhi,amit@gmail.com,28.0,1/10/2025,12500.0
1,2,Priya Rao,Chennai,priya@gmail.com,34.0,1/15/2025,22000.0
2,3,Rahul Verma,Mumbai,rahul@gmail.com,41.0,2/2/2025,18500.0
3,4,Sneha Iyer,Bengaluru,sneha@gmail.com,29.0,2/12/2025,9800.0
4,5,Kiran Kumar,Hyderabad,kiran@gmail.com,37.0,3/5/2025,31000.0

In [4]:
df.isnull().sum()

CustomerID       0
CustomerName     0
City             0
Email            0
Age              1
JoinDate         0
TotalPurchase    1
dtype: int64

In [5]:
df = df.drop_duplicates()

In [6]:
df["Age"] = df["Age"].fillna(df["Age"].median())
df["TotalPurchase"] = df["TotalPurchase"].fillna(0)

In [7]:
df["JoinDate"] = pd.to_datetime(df["JoinDate"])

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   CustomerID     10 non-null     int64
 1   CustomerName   10 non-null     str
 2   City           10 non-null     str
 3   Email          10 non-null     str
 4   Age            10 non-null     float64
 5   JoinDate       10 non-null     datetime64[us]
 6   TotalPurchase  10 non-null     float64
dtypes: datetime64[us](1), float64(2), int64(1), str(3)
memory usage: 692.0 bytes

In [9]:
total_revenue = df["TotalPurchase"].sum()

print("Total Revenue:", total_revenue)

Total Revenue: 155800.0

In [26]:
from sqlalchemy import create_engine

engine = create_engine(
    "mysql+pymysql://root:system@localhost/CustomerDB"
)
engine

Engine(mysql+pymysql://root:***@localhost/CustomerDB)

In [27]:
from sqlalchemy import text

with engine.connect() as conn:
    result = conn.execute(text("SELECT DATABASE();"))
    print(result.fetchone())

('customerdb',)

In [28]:
df.to_sql(
    "customers",
    con=engine,
    if_exists="replace",
    index=False
)

10

In [29]:
pd.read_sql("""
SELECT COUNT(*) AS TotalCustomers
FROM Customers
""", engine)

   TotalCustomers
0              10

In [30]:
pd.read_sql("""
SELECT CustomerID,
       CustomerName,
       TotalPurchase
FROM Customers
ORDER BY TotalPurchase DESC
LIMIT 5
""", engine)

   CustomerID CustomerName  TotalPurchase
0           5  Kiran Kumar        31000.0
1           9  Arjun Reddy        27800.0
2           2    Priya Rao        22000.0
3           3  Rahul Verma        18500.0
4           8   Neha Patel        15400.0

In [31]:
pd.read_sql("""
SELECT City,
       SUM(TotalPurchase) AS Revenue
FROM Customers
GROUP BY City
ORDER BY Revenue DESC
""", engine)

        City  Revenue
0    Chennai  49800.0
1  Hyderabad  31000.0
2     Mumbai  18500.0
3  Ahmedabad  15400.0
4      Delhi  12500.0
5      Kochi  11200.0
6  Bengaluru   9800.0
7       Pune   7600.0

In [32]:
pd.read_sql("""
SELECT City,
       COUNT(*) AS CustomerCount
FROM Customers
GROUP BY City
""", engine)

        City  CustomerCount
0      Delhi              2
1    Chennai              2
2     Mumbai              1
3  Bengaluru              1
4  Hyderabad              1
5       Pune              1
6  Ahmedabad              1
7      Kochi              1

In [33]:
pd.read_sql("""
SELECT *
FROM Customers
WHERE TotalPurchase >
(
    SELECT AVG(TotalPurchase)
    FROM Customers
)
""", engine)

,CustomerID,CustomerName,City,Email,Age,JoinDate,TotalPurchase
0,2,Priya Rao,Chennai,priya@gmail.com,34.0,2025-01-15,22000.0
1,3,Rahul Verma,Mumbai,rahul@gmail.com,41.0,2025-02-02,18500.0
2,5,Kiran Kumar,Hyderabad,kiran@gmail.com,37.0,2025-03-05,31000.0
3,9,Arjun Reddy,Chennai,arjun@gmail.com,39.0,2025-05-02,27800.0

In [34]:
pd.read_sql("""
SELECT CustomerID,
       CustomerName,
       TotalPurchase,
       RANK() OVER
       (
          ORDER BY TotalPurchase DESC
       ) AS CustomerRank
FROM Customers
""", engine)

   CustomerID  CustomerName  TotalPurchase  CustomerRank
0           5   Kiran Kumar        31000.0             1
1           9   Arjun Reddy        27800.0             2
2           2     Priya Rao        22000.0             3
3           3   Rahul Verma        18500.0             4
4           8    Neha Patel        15400.0             5
5           1   Amit Sharma        12500.0             6
6          10    Meera Nair        11200.0             7
7           4    Sneha Iyer         9800.0             8
8           6  Anjali Gupta         7600.0             9
9           7  Vikram Singh            0.0            10

In [35]:
pd.read_sql("""
SELECT MONTH(JoinDate) AS Month,
       COUNT(*) AS NewCustomers
FROM Customers
GROUP BY MONTH(JoinDate)
ORDER BY Month
""", engine)

   Month  NewCustomers
0      1             2
1      2             2
2      3             2
3      4             2
4      5             2